version: '3.7'
services:
  web:
    image: nginx
    container_name: web
    volumes:
      - ./docker/lorgant.conf:/etc/nginx/conf.d/lorgant.conf
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    build:
      context: ./docker
      dockerfile: php.docker
    container_name: php
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql/
  redis:
    image: redis
    container_name: redis
    volumes:
    - redisdata:/data
  nodejs:
    image: node:12-alpine
    container_name: nodejs
    volumes:
    - .:/app
    working_dir: /app
    tty: true
volumes:
  redisdata:
  dbdata:
    driver: local
